name: Update design-tokens-alpha-stable
on:
  push:
    branches:
      - main

jobs:
  update-design-tokens-alpha-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'

      - name: Set NPM version
        run: npm install -g npm@10.8.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install
        working-directory: grommet-leaflet

      - name: Build
        run: yarn build
        working-directory: grommet-leaflet

      - name: Update grommet-leaflet-stable
        run: |
          git config --global user.name "Grommet Community Bot"
          git config --global user.email "grommet@hpe.com"
          yarn release-stable
        working-directory: grommet-leaflet
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_ACCESS_TOKEN }}
